# Generated by Django 3.2.25 on 2024-12-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_project_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
    ]
